- hosts: provisioning_servers
  gather_facts: no
  tasks:
  - name: check for D drive
    win_stat:
      path: D:\
    register: d_exists
  - name: Copy TSCOWIN26 to D drive if D exists
    win_copy:
      src: /etc/ansible/assets/TSCOWIN26.zip
      dest: D:\TSCOWIN26.zip
    when: d_exists["stat"]["exists"]
  - name: unzip install file on D drive
    win_unzip:
      src: D:\TSCOWIN26.zip
      dest: D:\
      delete_archive: yes
    when: d_exists["stat"]["exists"]
  - name: Copy over script needed to run silent install
    win_copy:
      src: /etc/ansible/assets/new_run_cap_install.ps1
      dest: D:\TSCO_Agent_ver26.1.00\run_cap_install.ps1
    when: d_exists["stat"]["exists"]
  - name: run installer
    raw: D:\TSCO_Agent_ver26.1.00\run_cap_install.ps1
    when: d_exists["stat"]["exists"]
  - name: cleanup
    win_file:
      path: D:\TSCO_Agent_ver26.1.00
      state: absent
  - name: check for capacity agent
    win_service:
      name: BGS_SDService
      state: started
