- hosts: provisioning_servers
  gather_facts: no
  tasks:
  - name: check for D drive
    win_stat:
      path: D:\
    register: d_exists
  - name: Copy TSCOWIN2002 to D drive if D exists
    win_copy:
      src: /etc/ansible/assets/TSCOWIN2002.zip
      dest: D:\TSCOWIN2002.zip
    when: d_exists["stat"]["exists"]
  - name: Copy TSCOWIN2002 to C drive if D does not exist
    win_copy:
      src: /etc/ansible/assets/TSCOWIN2002.zip
      dest: C:\TSCOWIN2002.zip
    when: not d_exists["stat"]["exists"]
  - name: unzip install file on D drive
    win_unzip:
      src: D:\TSCOWIN2002.zip
      dest: D:\
      delete_archive: yes
    when: d_exists["stat"]["exists"]
  - name: unzip install file on C drive
    win_unzip:
      src: C:\TSCOWIN2002.zip
      dest: C:\
      delete_archive: yes
    when: not d_exists["stat"]["exists"]
  - name: Copy over script needed to run silent install
    win_copy:
      src: /etc/ansible/assets/run_cap_install.ps1
      dest: D:\TSCOWIN2002\run_cap_install.ps1
    when: d_exists["stat"]["exists"]
  - name: Copy over script needed to run silent install
    win_copy:
      src: /etc/ansible/assets/run_cap_install.ps1
      dest: D:\TSCOWIN2002\run_cap_install.ps1
    when: d_exists["stat"]["exists"]
  - name: Copy over script needed to run silent install
    win_copy:
      src: /etc/ansible/assets/run_cap_install.ps1
      dest: D:\TSCOWIN2002\run_cap_install.ps1
    when: d_exists["stat"]["exists"]
  - name: Copy over script needed to run silent install
    win_copy:
      src: /etc/ansible/assets/run_cap_install.ps1
      dest: C:\TSCOWIN2002\run_cap_install.ps1
    when: not d_exists["stat"]["exists"]
  - name: run installer
    raw: D:\TSCOWIN2002\run_cap_install.ps1
    when: d_exists["stat"]["exists"]
  - name: run installer
    raw: C:\TSCOWIN2002\run_cap_install.ps1
    when: not d_exists["stat"]["exists"]
  - name: cleanup
    win_file:
      path: D:\TSCOWIN2002
      state: absent
  - name: check for capacity agent
    win_service:
      name: BGS_SDService
      state: started
